export const HOME_ROUTE = '/'
export const SHOP_ROUTE = '/shop'
export const CART_ROUTE = '/cart'
export const PRODUCT_ROUTE = '/product'
export const ACCOUNT_ROUTE = '/account'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'